### ISSUE TITLE
It would be great if you could add rank also 

### ISSUE THREAD

**Issue by dewanhimanshu** [saranshbht/Project#1]

**Comment by saranshbht** [comment]
I did want to add a column for dynamically adding row number but since I am using deferRender while initializing the datatable not all rows are generated initially; they are only created when user navigates to that page number which messes up the numbering of the rows for the datatable. And saving the rank in my source data (json) would not allow me to be flexible since I use same records for class-wise and university-wise (concatenation of all class-wise records) results. But I will look to see if anything can be done. And you are more than welcome to open a PR. Thanks for your interest.
